# unwanted_senders = [
#     "invitations@linkedin.com",
#     "jobalert@timesjobs.com",
#     "hello@careercamp.codingninjas.com",
#     "english-personalized-digest@quora.com",
#     "no-reply@e.udemymail.com",
#     "alerts@info.netmeds.com",
#     "microsoft.start@email2.microsoft.com",
#     "support@fresherjobsz.com",
#     "noreply@glassdoor.com",
#     "noreply@medium.com",
#     "jobalerts-noreply@linkedin.com",
#     "technews@techgig.com",
#     "messaging-digest-noreply@linkedin.com",
#     "HSBC@custcomm.hsbc.co.in",
#     "do-not-reply@stackoverflow.email",
#     "info@jfhmails.co.in",
#     "expertspeak@techgig.com",
#     "noreply@jobs.unstop.news",
#     "sandeep@coachsandeepkhaira.com",
#     "hsbc@mail.hsbc.co.in",
#     "hsbc@informationservices.hsbc.co.in",
#     "team@cuvette.tech",
#     "no-reply@redbus.in",
#     "saudiara05-jobnotification@noreply23.jobs2web.com",
#     "greetings@travel.e-redbus.in",
#     "news@news.nl00.net",
#     "updates-noreply@linkedin.com",
#     "no-reply@geeksforgeeks.org",
#     "alert@indeed.com",
#     "mailgun@mg.breakthroughjuniorchallenge.org",
#     "no_reply@snapchat.com",
#     "naukrialerts@naukri.com",
#     "no-reply@swiggy.in",
#     "noreply@unstop.news",
#     "yashtechno-jobnotification@noreply10.jobs2web.com",
#     "aditi@talent500.co",

# ]
unwanted_senders = [
    "info@timesjobs.com","naukrialerts@naukri.com","ambitionbox@naukri.com"
]
